In [1]:
import numpy as np

In [4]:
my_list = [23, 45, 78]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([23, 45, 78])

In [7]:
my_mat = [[23, 897, 90], [80, 54, 23]]

In [8]:
multi_arr = np.array(my_mat)

In [9]:
multi_arr

array([[ 23, 897,  90],
       [ 80,  54,  23]])

In [10]:
type(arr)

numpy.ndarray

In [23]:
arr.dtype

dtype('int32')

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0, 10, 2)  # 2 is step size

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)   # generates one dimensional array

array([0., 0., 0.])

In [16]:
np.zeros((2, 3))    # pass a tuples for multidimensional array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(4) 

array([1., 1., 1., 1.])

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# generate evenly spaced number in given interval
np.linspace(0, 23, 12)    # third parameter is for how many numbers we need

array([ 0.        ,  2.09090909,  4.18181818,  6.27272727,  8.36363636,
       10.45454545, 12.54545455, 14.63636364, 16.72727273, 18.81818182,
       20.90909091, 23.        ])

In [24]:
# identity matrix
np.eye(4)  

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# random number generation
np.random.rand()     # generates one random number uniformly distributed from 0  to 1

0.09556247110817673

In [32]:
np.random.rand(5)   

array([0.87676092, 0.14684253, 0.27438723, 0.80229633, 0.1981051 ])

In [33]:
np.random.rand(5,4)

array([[0.49450109, 0.62735301, 0.50714396, 0.6718046 ],
       [0.7414068 , 0.90297041, 0.0483406 , 0.01328333],
       [0.51179115, 0.89133903, 0.7975564 , 0.06802191],
       [0.12025858, 0.34773399, 0.55818171, 0.4914446 ],
       [0.09532945, 0.37553258, 0.96092403, 0.14187394]])

In [39]:
# normal distribution 
np.random.randn()

-1.7087631450540455

In [38]:
np.random.randn(4)

array([-0.26697287, -1.0013497 ,  1.10460071,  0.5341529 ])

In [40]:
np.random.randn(2, 4)

array([[ 1.40191572, -1.41537406, -1.06308725, -0.40073891],
       [ 0.8379701 ,  0.88513226, -2.63021773, -1.11021195]])

In [42]:
# random integers (start, end, number_of_integers_needed)
np.random.randint(0, 13, 12)

array([ 4, 10,  2, 11, 11,  4,  7, 12,  6,  8,  4,  1])

In [46]:
arr_0_to_25 = np.arange(25)

In [47]:
arr_0_to_25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
randarr_0_to_25 = np.random.randint(0, 25, 25)

In [49]:
randarr_0_to_25

array([ 5, 20,  1, 24,  9,  7, 21, 12,  1,  8, 22, 23, 24, 14, 17,  2, 14,
       10,  0, 21, 17, 12,  5, 12, 17])

In [50]:
arr_0_to_25.reshape(5 , 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
randarr_0_to_25.max()

24

In [54]:
randarr_0_to_25.min()

0

In [55]:
# find index location of minimum value
randarr_0_to_25.argmin()

18

In [56]:
# find index location of maximum value
randarr_0_to_25.argmax()

3

In [57]:
arr_multi_0_to_25 = arr_0_to_25.reshape(5,5)

In [58]:
arr_multi_0_to_25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr_multi_0_to_25.shape

(5, 5)

In [60]:
arr.shape

(3,)

In [61]:
arr_multi_0_to_25.dtype

dtype('int32')